### ISSUE TITLE
Am able to install caffe but not appolocaffe

### ISSUE THREAD

**Issue by brettbj** [Russell91/apollocaffe#41]
I figured this didn't belong int he caffe users list - but I've succesfully built caffe, when I copy Makefile.config over and run -  make -j $(($(nproc) + 1)) I get a cython error:

makecython++ python/apollocaffe/cpp/_apollocaffe.pyx '' "-MMD -MP -pthread -fPIC -DNDEBUG -O2 -DWITH_PYTHON_LAYER -I/home/brett/anaconda3/include -I/home/brett/anaconda3/include/python3.5m -I/home/brett/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda/include -Wall -Wno-sign-compare -Wno-cpp -L/home/brett/anaconda3/lib -L/usr/local/lib -L/usr/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -L.build_release/lib  -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lboost_python -lpython2.7 -lopenblas -lboost_python -lpython2.7 -lcaffe" && rm python/apollocaffe/cpp/_apollocaffe.h

Error compiling Cython file:
------------------------------------------------------------
...
    def count(self):
        return self.thisptr.get().count()
    def dot(self, other):
        return self.DotPFrom(other)
    def norm(self):
        return self.dot(self) ** 0.5 / reduce(lambda x, y: x * y, self.shape)
                                            ^
------------------------------------------------------------

python/apollocaffe/cpp/_apollocaffe.pyx:82:45: undeclared name not builtin: reduce
python/apollocaffe/cpp/_apollocaffe.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
make: *** [apollo] Error 1

I've tried cython versions 0.17-0.23. Is there anything else I can try? Thanks for your help!

**Comment by Russell91** [comment]
Can you confirm that you are using python2.7?

**Comment by brettbj** [comment]
I didn't see your comment and started a fresh install. (I was using python3 and it seems to have worked with python2.7). I think you also need to use CUDNNv3 but installed without it for the time being this time. Thanks for your response!

**Comment by shwetgarg** [comment]
I am getting same error with 2.7 also. Any suggestion ?

**Comment by so-as** [comment]
@shwetgarg Hi, I had the same question as you. Did you solved the problem? wait for your reply, thx
